name: Go

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Disable GOPROXY
        run: go env -w GOPROXY=direct
      - name: Run tests
        run: go test -v -cover -failfast -vet=all -count=1 ./...
