name: Go

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Download dependencies
        run: cd testdata && go mod download
      - name: Run tests
        run: go test -v -cover -failfast -vet=all -count=1 ./...
